apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentclusterip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appclusterip
  template:
    metadata:
      labels:
        app: appclusterip
    spec:
      containers:
        - name: containerclusterip
          image: beingnaren/pyimage
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: appclusterip
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
